Repository naxatra36/repo1, pull requests merged in 2022-09, with the labels that each got.

#1 second commit
  add.py
Labels: hactober-accepted

#2 updated
  add.py
Labels: hactoberfest-accepted

#4 updated
  add.py
Labels: hacktoberfest-accepted

#5 updated
  add.py
Labels: hacktoberfest-accepted
